root = "."
tmp_dir = "tmp"

[build]
# bin = "./bin/app"
# bin = "dlv exec ./bin/app --listen=:2345 --headless=true "
# full_bin = "dlv exec ./bin/app --listen=:2345 --headless=true "
full_bin = "dlv exec --continue --accept-multiclient --listen=:2345 --headless=true --api-version=2 --log ./bin/app"

cmd = "templ generate && go build -o bin/app ./cmd/main.go"
# cmd = "templ generate && go build -o bin/app ./cmd/main.go"
delay = 1000
exclude_dir = ["bin", "assets", "tmp", "vendor"]
exclude_file = []
exclude_regex = [".*_templ.go"]
exclude_unchanged = false
follow_symlink = false
# full_bin = ""
include_dir = []
include_ext = ["go", "tpl", "tmpl", "templ", "html"]
kill_delay = "0s"
log = "build-errors.log"
send_interrupt = false
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = false

[misc]
clean_on_exit = false
